name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          major_pattern: 'major'
          minor_pattern: 'minor'
          version_format: '${major}.${minor}.${patch}-prerelease${increment}'
          debug: true
        id: version

      - name: Login docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: | 
          docker build -t dylanbatar/test-registry-render:${{ steps.version.outputs.version }} .
          docker build -t dylanbatar/test-registry-render .

      - name: Push image
        run: |
          docker push dylanbatar/test-registry-render:${{ steps.version.outputs.version }}
          docker push dylanbatar/test-registry-render
